# Generated by Django 5.1.1 on 2024-09-20 11:43

import django.db.models.deletion
import utils.code_utils
import utils.json_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.JSONField(default=utils.json_utils.default_localized_model),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.JSONField(default=utils.json_utils.default_localized_model),
                ),
                ('capacity', models.IntegerField(default=0)),
                ('location', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.JSONField(default=utils.json_utils.default_localized_model),
                ),
                ('link', models.URLField()),
                ('time', models.DateTimeField()),
                ('cast_name', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'poster',
                    models.FileField(
                        blank=True, null=True, upload_to=utils.code_utils.upload_to
                    ),
                ),
                ('author', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                (
                    'description',
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ('initial_reserved_seats', models.IntegerField(default=0)),
                ('reserved_seats', models.IntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                            ('SPAM', 'Spam'),
                            ('INAPPROPRIATE', 'Inappropriate'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='reviewed_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('tags', models.ManyToManyField(blank=True, to='show.showtag')),
                (
                    'theater',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='show.theater',
                    ),
                ),
            ],
        ),
    ]
