# Generated by Django 5.2 on 2025-04-30 22:22

import django.db.models.deletion
import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(blank=True, max_length=100, null=True)),
                ('jury_list', models.JSONField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('extra_details', models.JSONField(blank=True, null=True)),
                (
                    'logo',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.code_utils.upload_to_festival,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='crew',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='showtag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='festival',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='shows',
                to='show.festival',
            ),
        ),
    ]
