# Generated by Django 5.2 on 2025-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_festival_show_cast_show_crew_show_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='organizing_team',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='cast_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
