# Generated by Django 5.2 on 2025-05-09 23:17

import django.db.models.deletion
import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_festival_organizing_team_show_cast_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='description',
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(upload_to=utils.code_utils.upload_to_publication),
                ),
                (
                    'publication_number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'festival',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='show.festival',
                    ),
                ),
            ],
        ),
    ]
