# Generated by Django 5.2 on 2025-05-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_remove_show_description_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='festival',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='publications',
                to='show.festival',
            ),
        ),
        migrations.AlterField(
            model_name='show',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dates',
                        to='show.show',
                    ),
                ),
                (
                    'theater',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='theater_dates',
                        to='show.theater',
                    ),
                ),
            ],
        ),
    ]
