# Generated by Django 5.2 on 2025-05-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_alter_publication_festival_alter_show_link_showdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='show',
            name='time',
        ),
        migrations.AddConstraint(
            model_name='showdate',
            constraint=models.UniqueConstraint(
                fields=('date', 'time', 'theater'), name='unique_show_slot'
            ),
        ),
    ]
