# Generated by Django 5.2 on 2025-11-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_showdate_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='showdate',
            new_name='show_showda_show_id_6f4d01_idx',
            old_name='showdate_show_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='showdate',
            new_name='show_showda_date_0c2378_idx',
            old_name='showdate_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='showdate',
            new_name='show_showda_theater_c8acbc_idx',
            old_name='showdate_theater_date_time_idx',
        ),
    ]
