# Generated by Django 5.2 on 2026-03-11 19:16

import django.db.models.deletion
import utils.code_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('section_one', models.TextField(blank=True, null=True)),
                ('section_two', models.TextField(blank=True, null=True)),
                ('section_three', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                (
                    'article_type',
                    models.CharField(
                        choices=[
                            ('ARTICLE', 'Article'),
                            ('SYMPOSIA', 'Symposia'),
                            ('CREATIVITY', 'Creativity'),
                        ],
                        default='ARTICLE',
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='GlobalFestival',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('extra_details', models.JSONField(blank=True, null=True)),
                (
                    'logo',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.code_utils.upload_to_global_festival,
                    ),
                ),
                ('organizer', models.CharField(blank=True, max_length=100, null=True)),
                ('jury_list', models.JSONField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('organizing_team', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=utils.code_utils.upload_to_global_festival_article_attachment
                    ),
                ),
                ('position', models.IntegerField(default=0)),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='article_attachments',
                        to='global_festival.article',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='festival',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='festival_articles',
                to='global_festival.globalfestival',
            ),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                (
                    'poster',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.code_utils.upload_to_global_festival_show,
                    ),
                ),
                ('author', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('reserved_seats', models.IntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                            ('SPAM', 'Spam'),
                            ('INAPPROPRIATE', 'Inappropriate'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('cast', models.JSONField(blank=True, null=True)),
                ('crew', models.JSONField(blank=True, null=True)),
                ('cast_word', models.TextField(blank=True, null=True)),
                ('show_description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_location', models.URLField()),
                ('allowed_seats', models.IntegerField()),
                ('allowed_waiting', models.IntegerField()),
                ('reservation_status_open', models.BooleanField(default=False)),
                ('open_for_comments', models.BooleanField(default=False)),
                (
                    'festival',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='shows',
                        to='global_festival.globalfestival',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('reservation_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'has_attended',
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name='reservations',
                        to='global_festival.show',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('APPROVED', 'Approved'),
                            ('PENDING', 'Pending'),
                            ('REJECTED', 'Rejected'),
                            ('INAPPROPRIATE', 'Inappropriate'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'approved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='global_festival_approved_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='global_festival.show',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='show_articles',
                to='global_festival.show',
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='global_festival.tag'),
        ),
    ]
