services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5533:5432"
  admin:
    container_name: admin
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    entrypoint: []
volumes:
  data:
