services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5533:5432"
  admin:
    container_name: admin
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  data:
