# Generated by Django 5.2 on 2025-08-09 12:46

import django.db.models.deletion
import utils.code_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'file',
                    models.FileField(
                        upload_to=utils.code_utils.upload_to_script,
                        validators=[utils.code_utils.validate_file_extension],
                    ),
                ),
                ('author', models.CharField(max_length=50)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                            ('SPAM', 'Spam'),
                            ('INAPPROPRIATE', 'Inappropriate'),
                        ],
                        default='PENDING',
                        max_length=50,
                    ),
                ),
                ('year', models.IntegerField(blank=True, null=True)),
                (
                    'genre',
                    models.CharField(
                        choices=[
                            ('DRAMA', 'Drama'),
                            ('COMEDY', 'Comedy'),
                            ('TRAGEDY', 'Tragedy'),
                            ('ROMANCE', 'Romance'),
                            ('THRILLER', 'Thriller'),
                            ('FANTASY', 'Fantasy'),
                            ('SCIENCE_FICTION', 'Science Fiction'),
                            ('HORROR', 'Horror'),
                            ('MYSTERY', 'Mystery'),
                            ('ACTION', 'Action'),
                        ],
                        default='DRAMA',
                        max_length=50,
                    ),
                ),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                (
                    'cover',
                    models.ImageField(upload_to=utils.code_utils.upload_to_script),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='script_created_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='script_reviewed_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='script_updated_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
