# Generated by Django 5.2 on 2025-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita_arab_festival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='section_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='reservation_status_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='hita_arab_festival.tag'),
        ),
    ]
