# Generated by Django 5.2 on 2025-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'hita_arab_festival',
            '0002_tag_article_section_one_article_section_three_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='open_for_comments',
            field=models.BooleanField(default=False),
        ),
    ]
