# Generated by Django 5.2.9 on 2026-08-19 14:14

import django.db.models.deletion
import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_spaces_festival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=utils.code_utils.upload_to_alt_spaces_festival_publication
                    ),
                ),
                (
                    'publication_number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'festival',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='publications',
                        to='alt_spaces_festival.altspacesfestival',
                    ),
                ),
            ],
        ),
    ]
