import environ

env = environ.Env()

ACTOGRAM_FE_URL = env.str("FE_URL", default="http://localhost:8000")
SHOW_NIGHT_FE_URL = env.str("SHOW_NIGHT_URL", default="http://localhost:8000")
HITA_AF_FE_URL = env.str("HITA_AF_FE_URL", default="http://localhost:8000")
GLOBAL_FESTIVAL_FE_URL = env.str("GLOBAL_FESTIVAL_FE_URL", default="http://localhost:5174")
BE_URL = env.str("BASE_URL", default="http://localhost:8000")
GOOGLE_CLIENT_ID = env.str('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env.str('GOOGLE_CLIENT_SECRET', default='')
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_SIGNATURE_NAME = env.str('AWS_S3_SIGNATURE_NAME', default='')
AWS_S3_REGION_NAME = env.str('AWS_S3_REGION_NAME', default='')
ACCESS_TOKEN_LIFETIME = env.int('ACCESS_TOKEN_LIFETIME', default=5)
REFRESH_TOKEN_LIFETIME = env.int('REFRESH_TOKEN_LIFETIME', default=30)
ENVIRONMENT = env.str("ENVIRONMENT", default="local")
OPENAI_API_KEY = env.str("OPENAI_API_KEY", default="")
OPENAI_TEXT_MODEL = env.str("OPENAI_TEXT_MODEL", default="gpt-4.1-mini")
OPENAI_VISION_MODEL = env.str("OPENAI_VISION_MODEL", default="gpt-4.1-mini")
OPENAI_EMBED_MODEL = env.str("OPENAI_EMBED_MODEL", default="text-embedding-3-small")
SEND_EMAIL = env.bool("SEND_EMAIL", default=False)
