# Generated by Django 5.1.1 on 2024-11-11 02:07

import django.db.models.deletion
import utils.code_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterRoles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('ACTOR', 'Actor/Actress'),
                            ('AUTHOR', 'Author'),
                            ('TREATMENT', 'Treatment'),
                            ('DIRECTOR', 'Director'),
                            ('DIRECTING_CAST', 'Directing Cast'),
                            ('DECOR', 'Decor'),
                            ('STYLING', 'Styling'),
                            ('MAKEUP', 'Makeup'),
                            ('LIGHTING', 'Lighting'),
                            ('COMPOSING', 'Composing'),
                            ('MUSIC_ARRANGEMENT', 'Music Arrangement'),
                            ('MUSICIAN', 'Musician'),
                            ('CHOREOGRAPHY', 'Choreography'),
                            ('DANCER', 'Dancer'),
                        ],
                        default='ACTOR',
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HITAMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                (
                    'grade',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 'First'),
                            (2, 'Second'),
                            (3, 'Third'),
                            (4, 'Forth'),
                        ],
                        null=True,
                    ),
                ),
                (
                    'department',
                    models.CharField(
                        choices=[
                            ('ACTING', 'Acting And Directing'),
                            ('DRAMA', 'Drama And Criticism'),
                            ('DECOR', 'Decor'),
                        ],
                        default='ACTING',
                        max_length=10,
                    ),
                ),
                (
                    'study_type',
                    models.CharField(
                        choices=[('NORMAL', 'Normal'), ('PARALLEL', 'Parallel')],
                        default='NORMAL',
                        max_length=15,
                    ),
                ),
                ('is_graduated', models.BooleanField(default=False)),
                ('year_of_graduation', models.IntegerField(blank=True, null=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('AVAILABLE', 'Available'),
                            ('NOT_AVAILABLE', 'Not Available'),
                        ],
                        default='AVAILABLE',
                        max_length=20,
                    ),
                ),
                ('account_protected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'hita_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='hita.hitamember',
                    ),
                ),
                (
                    'white_list_members',
                    models.ManyToManyField(
                        blank=True,
                        related_name='white_list_members',
                        to='hita.hitamember',
                    ),
                ),
                (
                    'skills_tags',
                    models.ManyToManyField(blank=True, to='hita.theaterroles'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='hitamember',
            name='favorite_performers',
            field=models.ManyToManyField(blank=True, to='hita.performer'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=utils.code_utils.get_upload_path)),
                ('is_profile_picture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='galleries',
                        to='hita.performer',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'contact_type',
                    models.CharField(
                        choices=[
                            ('MOBILE', 'Mobile'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('FACEBOOK', 'Facebook'),
                            ('INSTAGRAM', 'Instagram'),
                            ('TIK_TOK', 'TikTok'),
                            ('YOUTUBE', 'YouTube'),
                            ('TWITTER', 'Twitter'),
                            ('OTHER', 'Other'),
                        ],
                        default='MOBILE',
                        max_length=20,
                    ),
                ),
                ('contact_info', models.CharField(max_length=100)),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contact_details_list',
                        to='hita.performer',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('position', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('show_name', models.CharField(max_length=100)),
                ('festival_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='achievements',
                        to='hita.performer',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('show_name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='experiences',
                        to='hita.performer',
                    ),
                ),
                ('role', models.ManyToManyField(to='hita.theaterroles')),
            ],
        ),
    ]
