# Generated by Django 5.1.3 on 2025-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitamember',
            name='invitation_code',
            field=models.CharField(default='44c2ea3092f44c0dacb8', max_length=20),
        ),
    ]
