# Generated by Django 5.1.3 on 2024-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='account_protected',
            new_name='contact_detail_protected',
        ),
        migrations.AddField(
            model_name='performer',
            name='biography',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='gallery_protected',
            field=models.BooleanField(default=False),
        ),
    ]
