# Generated by Django 5.1.3 on 2024-12-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='contactdetail',
            options={'ordering': ('contact_type',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='publicchannel',
            options={'ordering': ('channel_type',)},
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(
                choices=[
                    ('MOBILE', 'Mobile'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('FACEBOOK', 'Facebook'),
                    ('INSTAGRAM', 'Instagram'),
                    ('TIK_TOK', 'TikTok'),
                    ('YOUTUBE', 'YouTube'),
                    ('TWITTER', 'Twitter'),
                    ('SHOWREEL', 'ShowReel'),
                    ('VIMEO', 'Vimeo'),
                    ('BEHANCE', 'Behance'),
                    ('GOOGLE_DRIVE', 'Google Drive'),
                    ('OTHER', 'Other'),
                ],
                default='MOBILE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='publicchannel',
            name='channel_type',
            field=models.CharField(
                choices=[
                    ('MOBILE', 'Mobile'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('FACEBOOK', 'Facebook'),
                    ('INSTAGRAM', 'Instagram'),
                    ('TIK_TOK', 'TikTok'),
                    ('YOUTUBE', 'YouTube'),
                    ('TWITTER', 'Twitter'),
                    ('SHOWREEL', 'ShowReel'),
                    ('VIMEO', 'Vimeo'),
                    ('BEHANCE', 'Behance'),
                    ('GOOGLE_DRIVE', 'Google Drive'),
                    ('OTHER', 'Other'),
                ],
                default='YOUTUBE',
                max_length=20,
            ),
        ),
    ]
