# Generated by Django 5.1.3 on 2025-01-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0002_hitamember_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitamember',
            name='invitation_code',
            field=models.CharField(default='9197f4902a904918ab64', max_length=20),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'from_member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='referrer',
                        to='hita.hitamember',
                    ),
                ),
                (
                    'invited_member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='referred',
                        to='hita.hitamember',
                    ),
                ),
            ],
        ),
    ]
