# Generated by Django 5.1.3 on 2024-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'hita',
            '0002_rename_account_protected_performer_contact_detail_protected_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='hitamember',
            name='gender',
            field=models.CharField(
                choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1
            ),
            preserve_default=False,
        ),
    ]
