# Generated by Django 5.1.3 on 2024-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0002_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contact_type',
            field=models.CharField(
                choices=[
                    ('MOBILE', 'Mobile'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('FACEBOOK', 'Facebook'),
                    ('INSTAGRAM', 'Instagram'),
                    ('TIK_TOK', 'TikTok'),
                    ('YOUTUBE', 'YouTube'),
                    ('TWITTER', 'Twitter'),
                    ('SHOWREEL', 'ShowReel'),
                    ('VIMEO', 'Vimeo'),
                    ('BEHANCE', 'Behance'),
                    ('GOOGLE_DRIVE', 'Google Drive'),
                    ('TELEGRAM', 'Telegram'),
                    ('SOUND_CLOUD', 'SoundCloud'),
                    ('OTHER', 'Other'),
                ],
                default='MOBILE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='publicchannel',
            name='channel_type',
            field=models.CharField(
                choices=[
                    ('MOBILE', 'Mobile'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('FACEBOOK', 'Facebook'),
                    ('INSTAGRAM', 'Instagram'),
                    ('TIK_TOK', 'TikTok'),
                    ('YOUTUBE', 'YouTube'),
                    ('TWITTER', 'Twitter'),
                    ('SHOWREEL', 'ShowReel'),
                    ('VIMEO', 'Vimeo'),
                    ('BEHANCE', 'Behance'),
                    ('GOOGLE_DRIVE', 'Google Drive'),
                    ('TELEGRAM', 'Telegram'),
                    ('SOUND_CLOUD', 'SoundCloud'),
                    ('OTHER', 'Other'),
                ],
                default='YOUTUBE',
                max_length=20,
            ),
        ),
    ]
