# Generated by Django 5.1.3 on 2024-11-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0003_hitamember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitamember',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
