# Generated by Django 5.1.3 on 2024-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0003_alter_contactdetail_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='producer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_brief',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='director',
            field=models.CharField(max_length=20),
        ),
    ]
