# Generated by Django 5.2 on 2025-05-28 14:50

import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0003_alter_hitamember_invitation_code_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitamember',
            name='invitation_code',
            field=models.CharField(
                default=utils.code_utils.generate_invitation_code, max_length=20
            ),
        ),
    ]
