# Generated by Django 5.1.3 on 2025-01-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0003_alter_hitamember_invitation_code_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitamember',
            name='faculty',
            field=models.CharField(
                choices=[
                    ('THEATER_INST', 'Theater Institute'),
                    ('CINEMA_INST', 'Cinema Institute'),
                ],
                default='THEATER_INST',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='hitamember',
            name='department',
            field=models.CharField(
                choices=[
                    ('ACTING_DEP', 'Acting And Directing'),
                    ('DRAMA_DEP', 'Drama And Criticism'),
                    ('DECOR_DEP', 'Decor'),
                    ('TECH_DEP', 'Theatrical Techniques'),
                    ('SCREENWRITING_DEP', 'Screenwriting'),
                    ('CINEMATOGRAPHY_DEP', 'CINEMATOGRAPHY'),
                    ('DIRECTING_DEP', 'Directing'),
                    ('ANIMATION_DEP', 'Animation'),
                    ('EDITING_DEP', 'Editing'),
                    ('PRODUCTION_DEP', 'Production'),
                    ('SOUND_ENGINEERING_DEP', 'Sound Engineering'),
                    ('SET_DESIGN_DEP', 'Set Design'),
                ],
                default='ACTING_DEP',
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='hitamember',
            name='invitation_code',
            field=models.CharField(max_length=20),
        ),
    ]
