# Generated by Django 5.2 on 2025-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0004_alter_hitamember_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterrole',
            name='name',
            field=models.CharField(
                choices=[
                    ('ACTOR', 'Actor/Actress'),
                    ('AUTHOR', 'Author'),
                    ('TREATMENT', 'Treatment'),
                    ('DIRECTOR', 'Director'),
                    ('DIRECTING_CAST', 'Directing Cast'),
                    ('DECOR', 'Decor'),
                    ('STYLING', 'Styling'),
                    ('MAKEUP', 'Makeup'),
                    ('LIGHTING', 'Lighting'),
                    ('COMPOSING', 'Composing'),
                    ('MUSIC_ARRANGEMENT', 'Music Arrangement'),
                    ('MUSIC_PREPARATION', 'Music Preparation'),
                    ('MUSICIAN', 'Musician'),
                    ('CHOREOGRAPHY', 'Choreography'),
                    ('DANCER', 'Dancer'),
                    ('SINGING', 'Singing'),
                    ('VIDEOGRAPHY', 'Videography'),
                    ('PHOTOGRAPHY', 'Photography'),
                    ('VIDEO_MAPPING', 'Video Mapping'),
                    ('GRAPHICS_DESIGNER', 'Graphics Designer'),
                    ('HAIR_DRESSER', 'Hair Dresser'),
                ],
                default='ACTOR',
                max_length=40,
            ),
        ),
    ]
