# Generated by Django 5.1.3 on 2024-12-15 22:52

import django.db.models.deletion
import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0004_experience_producer_experience_role_brief_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowReel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=utils.code_utils.get_upload_path,
                        validators=[utils.code_utils.validate_file_size],
                    ),
                ),
                (
                    'performer',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='show_reel',
                        to='hita.performer',
                    ),
                ),
            ],
        ),
    ]
