# Generated by Django 5.1.3 on 2025-01-11 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0004_hitamember_faculty_alter_hitamember_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HITAMember',
            new_name='Member',
        ),
    ]
