# Generated by Django 5.1.3 on 2024-11-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0004_hitamember_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='hita_member',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='performer',
                to='hita.hitamember',
            ),
        ),
    ]
