# Generated by Django 5.1.3 on 2024-12-15 23:03

import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0005_showreel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showreel',
            name='file',
            field=models.FileField(
                storage='storages.backends.s3boto3.S3Boto3Storage',
                upload_to='',
                validators=[utils.code_utils.validate_file_size],
            ),
        ),
    ]
