# Generated by Django 5.1.3 on 2025-01-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0005_rename_hitamember_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='hita.member',
            ),
        ),
    ]
