# Generated by Django 5.1.3 on 2024-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0005_alter_performer_hita_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='open_for',
            field=models.CharField(
                choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('BOTH', 'Both')],
                default='FREE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='performer',
            name='status',
            field=models.CharField(
                choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')],
                default='AVAILABLE',
                max_length=20,
            ),
        ),
    ]
