# Generated by Django 5.1.3 on 2025-01-16 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0005_rename_hitamember_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.CreateModel(
            name='AdminMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                (
                    'location',
                    models.CharField(
                        choices=[('CAIRO', 'Cairo'), ('ALEXANDRIA', 'Alexandria')],
                        default='CAIRO',
                        max_length=15,
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'permissions': [
                    (
                        'can_approve_all_member_requests',
                        'Can approve all member request',
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='hita.adminmember',
            ),
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'request_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                            ('BLOCKED', 'Blocked'),
                        ],
                        default='PENDING',
                        max_length=10,
                    ),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'gender',
                    models.CharField(
                        choices=[('M', 'Male'), ('F', 'Female')], max_length=1
                    ),
                ),
                ('invitation_code', models.CharField(max_length=20)),
                (
                    'location',
                    models.CharField(
                        choices=[('CAIRO', 'Cairo'), ('ALEXANDRIA', 'Alexandria')],
                        default='CAIRO',
                        max_length=15,
                    ),
                ),
                ('is_individual', models.BooleanField(default=False)),
                (
                    'casting_agency_name',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'mobile_number',
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ('facebook_page', models.URLField(blank=True, null=True)),
                (
                    'favorite_performers',
                    models.ManyToManyField(blank=True, to='hita.performer'),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='hita.adminmember',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
