# Generated by Django 5.1.3 on 2024-12-15 23:08

import storages.backends.s3
import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0006_alter_showreel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showreel',
            name='file',
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to='',
                validators=[utils.code_utils.validate_file_size],
            ),
        ),
    ]
