# Generated by Django 5.1.3 on 2024-12-17 01:17

import utils.code_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0007_alter_showreel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='showreel',
            name='thumbnail',
            field=models.FileField(
                blank=True, null=True, upload_to=utils.code_utils.get_upload_path
            ),
        ),
    ]
