# Generated by Django 5.1.3 on 2024-12-17 01:19

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0008_showreel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showreel',
            name='thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to='',
            ),
        ),
    ]
