# Generated by Django 5.1.3 on 2024-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0010_alter_showreel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='festival_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
