# Generated by Django 5.1.3 on 2024-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0011_experience_festival_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitamember',
            name='is_post_grad',
            field=models.BooleanField(default=False),
        ),
    ]
