# Generated by Django 5.1.3 on 2024-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hita', '0013_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitamember',
            name='department',
            field=models.CharField(
                choices=[
                    ('ACTING_DEP', 'Acting And Directing'),
                    ('DRAMA_DEP', 'Drama And Criticism'),
                    ('DECOR_DEP', 'Decor'),
                    ('TECH_DEP', 'Theatrical Techniques'),
                ],
                default='ACTING_DEP',
                max_length=10,
            ),
        ),
    ]
