# Generated by Django 5.2 on 2025-11-20 23:32

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('hita', '0005_alter_theaterrole_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerInsights',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('features', models.JSONField(blank=True, default=dict)),
                ('role_stats', models.JSONField(blank=True, default=dict)),
                (
                    'vec_profile',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    'vec_skills',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    'source_version',
                    models.CharField(blank=True, default='v1', max_length=32),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'performer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='insights',
                        to='hita.performer',
                    ),
                ),
            ],
        ),
    ]
