# Generated by Django 5.1.1 on 2024-09-10 21:22

import django.db.models.deletion
import utils.json_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.JSONField(default=utils.json_utils.default_localized_model),
                ),
                ('capacity', models.IntegerField(default=0)),
                ('location', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.JSONField(default=utils.json_utils.default_localized_model),
                ),
                ('link', models.URLField()),
                ('time', models.DateTimeField()),
                ('initial_reserved_seats', models.IntegerField(default=0)),
                ('reserved_seats', models.IntegerField(default=0)),
                (
                    'theater',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='ticket.theater',
                    ),
                ),
            ],
        ),
    ]
